version: '3'

services:
  redis:
    image: redis:alpine
  postgres:
    image: postgres:13
    command: postgres -c log_statement=all
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A aviator_bot_backend.celery worker -l info
    environment:
      - PIP_DEFAULT_TIMEOUT=100
      - DATABASE=postgres
    env_file:
      - ./.envrc
    volumes:
      - ./:/app/
    depends_on:
      - postgres
      - redis
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A aviator_bot_backend.celery beat -l info
    environment:
      - PIP_DEFAULT_TIMEOUT=100
      - DATABASE=postgres
    env_file:
      - ./.envrc
    volumes:
      - ./:/app/
    depends_on:
      - postgres
      - redis
  worker:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - PIP_DEFAULT_TIMEOUT=100
      - DATABASE=postgres
    env_file:
      - ./.envrc
    ports:
      - '8000:8000'
    volumes:
      - ./:/app/
    depends_on:
      - postgres
      - redis
    links:
      - redis
volumes:
  postgres_data:
